services:
  - type: web
    name: motorwae-api
    runtime: node
    rootDir: apps/api
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 5000
